"use client";
import { useEffect, useState } from "react";
import { api, ApiError, LinkRecord, StatsSummary } from "@/lib/api-client";

export default function Dashboard() {
  const [stats, setStats] = useState<StatsSummary | null>(null); const [links, setLinks] = useState<LinkRecord[]>([]); const [error, setError] = useState("");
  useEffect(() => { Promise.all([api.stats.summary(), api.links.list({ limit: 5, sort: "created_at_desc" })]).then(([summary, page]) => { setStats(summary); setLinks(page.links || []); }).catch(e => setError(e instanceof ApiError ? e.message : "加载失败")); }, []);
  return <div className="space-y-7"><div><p className="text-sm text-[var(--muted)]">工作台</p><h1 className="mt-1 text-2xl font-bold tracking-tight">概览</h1></div>{error && <p className="rounded-lg bg-red-50 px-4 py-3 text-red-700">{error}</p>}<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[["总链接数", stats?.total_links ?? 0], ["累计点击", stats?.total_clicks ?? 0], ["服务状态", "正常"]].map(([label, value]) => <div className="panel p-5" key={String(label)}><p className="text-sm text-[var(--muted)]">{label}</p><p className="mt-3 text-3xl font-bold">{value}</p></div>)}</div><section className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-[var(--line)] px-5 py-4"><h2 className="font-semibold">最近链接</h2><a href="/admin/links" className="text-sm font-medium text-[var(--brand)]">查看全部</a></div><div className="divide-y divide-[var(--line)]">{links.length ? links.map(link => <div className="flex items-center justify-between gap-4 px-5 py-4" key={link.id}><div className="min-w-0"><p className="font-medium">/{link.alias}</p><p className="truncate text-sm text-[var(--muted)]">{link.destination_url}</p></div><div className="flex shrink-0 items-center gap-3"><span className="text-sm text-[var(--muted)] tabular-nums">{link.clicks ?? 0} 次点击</span><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs text-emerald-700">{link.status}</span></div></div>) : <p className="px-5 py-8 text-center text-sm text-[var(--muted)]">暂无链接</p>}</div></section></div>;
}
